title: Inside Access
description: Resources for Small Group Leaders

url: https://ottolopez.github.io
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: QR Code Generator
      url: /qrgenerator
    - title: Contact
      url: /contact
      

social:
    facebook: AccessChurchGuatemala
    email: otto@access.gt
    youtube: AccessChurchGuatemala
