title: Inside Access
email: otto@access.gt
description: >- 
  Life is better connected
baseurl: "" # Leave empty unless your site is in a subdirectory
url: "https://ottolopez.github.io" # Replace <username> with your GitHub username
theme: minima

minima:
  skin: dark # Choose from 'classic', 'dark', 'auto', etc.
  show_excerpts: true # Show post excerpts on the home page