// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msldnioxbwgqvbiepppw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zbGRuaW94YndncXZiaWVwcHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzk4OTgsImV4cCI6MjA2OTg1NTg5OH0.iq8npBFj_CtxDji2nj_Hy_Kmyxr-a3YLUDnShG_FFdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});